# Generated by Django 2.2.1 on 2019-06-17 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ipl_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='umpire2',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
    ]
